# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d853797b5cbe0833931063c35760b41240e845614e70ddc36e6b915aff99bc0a9bc7cc65327fb2cbc68b36e5b4cf71e6b9c766706e80052e7f38f1d690bd19b9

test:
  secret_key_base: 3dc3b31c1a30c10d5eec7e10c4ad56bc81359246705badda381ef693746b86f43cc8ad2d4c1a08011c4da8ed424a523e3d72036b063f7273d586fc6cd5c3524f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
